import requests
import base64
from nacl import pwhash, utils, secret

from utils import API_TOKEN, PLAINTEXT_MESSAGE, process_response

PSP_SEND_URL = 'https://whoomp.cs.uwaterloo.ca/458a3/api/psp/send'
PSP = 'poor respondent'
SALT = '91da7bc55ad6846923316d99c171d3b16e518518fa32e7a461f4bf4be346c232'
OP_LIMIT = 524288
MEM_LIMIT = 16777216

# Decode salt
decoded_salt = base64.b16decode(SALT.upper())
print 'Decoded salt is: {}'.format(decoded_salt)

# Generate secret key by hashing
secret_key = pwhash.kdf_scryptsalsa208sha256(secret.SecretBox.KEY_SIZE, PSP, decoded_salt, 
		  		 							 opslimit=OP_LIMIT, memlimit=MEM_LIMIT)
print 'Secret key generated by hashing password is: {}'.format(secret_key)

# Create secret box
secret_box = secret.SecretBox(secret_key)

# Encrypt and encode message
encrypted_message = secret_box.encrypt(PLAINTEXT_MESSAGE)
print 'Encrypted message is: {}'.format(encrypted_message)

encoded_message = base64.b64encode(encrypted_message)
print 'Base 64 encoded encrypted message is: {}'.format(encoded_message)

# Send message
data = {
	'api_token': API_TOKEN,
	'to': 'jessie',
	'message': encoded_message
}

response = requests.post(
	url=PSP_SEND_URL,
	data=data,
)

# Process response
process_response(response)