import requests
import base64
from nacl import pwhash, utils, secret

from utils import API_TOKEN, PLAINTEXT_MESSAGE, process_response

PSP_INBOX_URL = 'https://whoomp.cs.uwaterloo.ca/458a3/api/psp/inbox'
PSP = 'poor respondent'
SALT = '91da7bc55ad6846923316d99c171d3b16e518518fa32e7a461f4bf4be346c232'
OP_LIMIT = 524288
MEM_LIMIT = 16777216

# Decode salt
decoded_salt = base64.b16decode(SALT.upper())
print 'Decoded salt is: {}'.format(decoded_salt)

# Generate secret key by hashing
secret_key = pwhash.kdf_scryptsalsa208sha256(secret.SecretBox.KEY_SIZE, PSP, decoded_salt, 
		  		 							 opslimit=OP_LIMIT, memlimit=MEM_LIMIT)
print 'Secret key generated by hashing password is: {}'.format(secret_key)

# Create secret box
secret_box = secret.SecretBox(secret_key)

# Send inbox request
data = {
	'api_token': API_TOKEN,
}

response = requests.post(
	url=PSP_INBOX_URL,
	data=data,
)

# Process response
def decode_decrypt_and_print_messages(messages):
	for message in messages:
		encrypted_message = base64.b64decode(message['message'])
		decrypted_message = secret_box.decrypt(encrypted_message)
		print 'Message: {}'.format(decrypted_message)

process_response(response, process_messages=decode_decrypt_and_print_messages)